// src/pages/TermsOfService.jsx
import { Link } from 'react-router-dom'

export default function TermsOfService() {
  return (
    <div style={{
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #0A1F10 0%, #1B4D2E 50%, #2D7A47 100%)',
      padding: '100px 20px',
      fontFamily: "'Inter', system-ui, sans-serif",
    }}>
      <div style={{
        maxWidth: 900,
        margin: '0 auto',
        background: 'rgba(255,255,255,0.96)',
        borderRadius: 32,
        boxShadow: '0 25px 50px -12px rgba(0,0,0,0.35)',
        overflow: 'hidden',
      }}>
        <div style={{
          background: 'linear-gradient(135deg, #1B4D2E, #2D7A47)',
          padding: '32px 40px',
          borderBottom: '1px solid rgba(255,255,255,0.1)',
        }}>
          <h1 style={{
            color: 'white',
            fontSize: 28,
            fontWeight: 800,
            margin: 0,
            display: 'flex',
            alignItems: 'center',
            gap: 12,
          }}>
            <span style={{ fontSize: 32 }}>📜</span> Terms of Service
          </h1>
          <p style={{ color: '#A7D9B5', margin: '8px 0 0', fontSize: 14 }}>
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </div>

        <div style={{ padding: '40px', lineHeight: 1.8, color: '#1a1a1a', fontSize: 15 }}>

          <h2 style={{ color: '#2D7A47', fontSize: 20, marginTop: 0, marginBottom: 12 }}>1. Acceptance of Terms</h2>
          <p>By accessing or using KisanAI (website, mobile app, or API), you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform.</p>

          <h2 style={{ color: '#2D7A47', fontSize: 20, marginTop: 32, marginBottom: 12 }}>2. Description of Service</h2>
          <p>KisanAI is a <strong>free, educational AI‑powered farming assistant</strong> designed for Pakistani farmers. It provides:</p>
          <ul>
            <li>Crop disease detection (via photo upload).</li>
            <li>Fertilizer and spray calculator recommendations.</li>
            <li>Weather forecasts and mandi prices.</li>
            <li>Yield prediction and expense tracking.</li>
            <li>Community forum and farmer advisory.</li>
          </ul>
          <p>All advice generated by AI is <strong>for informational purposes only</strong> and should not replace professional agronomist consultation.</p>

          <h2 style={{ color: '#2D7A47', fontSize: 20, marginTop: 32, marginBottom: 12 }}>3. User Responsibilities</h2>
          <ul>
            <li>You must provide accurate information during registration.</li>
            <li>You are responsible for any decisions you make based on AI recommendations. KisanAI and its developers are <strong>not liable</strong> for crop loss or damages.</li>
            <li>You must not upload offensive, illegal, or harmful images/content (e.g., violence, pornography, hate speech).</li>
            <li>You must not misuse the AI (e.g., automated scripts, excessive requests).</li>
            <li>You must respect other community members – no harassment or spam.</li>
          </ul>

          <h2 style={{ color: '#2D7A47', fontSize: 20, marginTop: 32, marginBottom: 12 }}>4. Account Termination</h2>
          <p>We reserve the right to suspend or terminate your account if you violate these terms (e.g., abusive behavior, illegal content). You may delete your own account at any time from Settings.</p>

          <h2 style={{ color: '#2D7A47', fontSize: 20, marginTop: 32, marginBottom: 12 }}>5. Disclaimer of Warranties</h2>
          <p>KisanAI is provided “as is” without any warranties. We do not guarantee:</p>
          <ul>
            <li>100% accuracy of AI predictions or diagnoses.</li>
            <li>Uninterrupted service (downtime may occur).</li>
            <li>That mandi prices or weather data are always real‑time or error‑free (data comes from third‑party APIs).</li>
          </ul>

          <h2 style={{ color: '#2D7A47', fontSize: 20, marginTop: 32, marginBottom: 12 }}>6. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, KisanAI and its developers (including UET Lahore) shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the platform – including loss of crops, financial loss, or data loss.</p>

          <h2 style={{ color: '#2D7A47', fontSize: 20, marginTop: 32, marginBottom: 12 }}>7. Changes to Terms</h2>
          <p>We may update these terms occasionally. We will notify you of significant changes via email or in‑app banner. Continued use after changes constitutes acceptance.</p>

          <h2 style={{ color: '#2D7A47', fontSize: 20, marginTop: 32, marginBottom: 12 }}>8. Contact</h2>
          <p>For any questions, please reach out via the feedback form in the app or email: <strong>kisanai.noreply@gmail.com</strong>.</p>

          <div style={{
            marginTop: 48,
            paddingTop: 24,
            borderTop: '1px solid #E8F4E8',
            textAlign: 'center',
            fontSize: 13,
            color: '#666',
          }}>
            <Link to="/" style={{ color: '#2D7A47', textDecoration: 'none', fontWeight: 600 }}>← Back to Home</Link>
            <span style={{ margin: '0 12px' }}>·</span>
            <Link to="/privacy" style={{ color: '#2D7A47', textDecoration: 'none', fontWeight: 600 }}>Privacy Policy</Link>
          </div>
        </div>
      </div>
    </div>
  )
}